name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"
  RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }} # Set in GitHub Secrets

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Django App

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 3. Install dependencies with caching
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run Django tests
        run: |
          mkdir -p staticfiles
          python manage.py test

      # 5. Build static files (for deployment)
      - name: Collect static files
        run: python manage.py collectstatic --noinput

  deploy:
    needs: build-and-test # Only run if build-and-test succeeds
    runs-on: ubuntu-latest
    name: Deploy to Render
    if: github.ref == 'refs/heads/main' # Only deploy on main branch pushes

    steps:
      # 1. Checkout code (needed for Render's deployment hook)
      - uses: actions/checkout@v4

      # 2. Trigger Render deployment
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Accept: application/vnd.render+json; version=1" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            ${{ env.RENDER_DEPLOY_HOOK }}
